import Work2 from "../../assets/projects/wordle.png";
import Work3 from "../../assets/projects/parkme.png";
import Work4 from "../../assets/projects/calculator.png";
import Work5 from "../../assets/projects/sketch.png";
import Work1 from "../../assets/projects/platepals.png";

export const projectsData = [
  {
    id: 1,
    video: "https://www.youtube.com/embed/EWE_8sm45_s",
    title: "Spotify to YouTube Playlist Converter",
    link: "https://spotify-youtube-convert-89a98418f1e9.herokuapp.com",
    stack: [
      "React",
      "Spotify API",
      "YouTube API",
      "Node.js",
      "Express.js",
      "Heroku",
      "Passport.js",
    ],
    description: "Convert your Spotify playlists to YouTube playlists.",
    github: "https://github.com/justinc0251/spotify-youtube-converter",
  },
  {
    id: 2,
    image: Work1,
    title: "PlatePals",
    link: "https://ssl.students.engr.scu.edu/~jdchung/PlatePals/home.php",
    stack: [
      "HTML",
      "CSS",
      "JavaScript",
      "PHP",
      "MySQL",
    ],
    description: "Recipe sharing website to connect culinary enthusiasts.",
    github: "https://github.com/asterli/PlatePals/",
  },
  {
    id: 3,
    video: "https://www.youtube.com/embed/-jPg9GvSo4s",
    title: "ClubHub",
    link: "https://www.club-hub.live/",
    stack: [
      "React",
      "JavaScript",
      "Firebase",
      "Node.js",
      "Open API",
      "Heroku",
    ],
    description: "Centralized platform for discovering and staying updated on club events at Santa Clara University.",
    github: "https://github.com/CSEN-SCU/csen-174-s24-project-clubhub",
  },
  {
    id: 4,
    video: "https://www.youtube.com/embed/EFEdL2b5tcU",
    title: "VitAlz",
    link: "https://devpost.com/software/vitalz",
    stack: [
      "Swift",
      "Xcode",
      "CoreML",
      "Firebase",
    ],
    description: "iOS app designed to educate and support Alzheimer's patients and caregivers through task tracking, memory exercises, and comprehensive resources.",
    github: "https://github.com/justinc0251/VitAlz",
  },
  {
    id: 5,
    video: "https://www.youtube.com/embed/_q2OEhN2obo",
    title: "Discord Music Bot",
    stack: [
      "JavaScript",
      "Node.js",
      "Discord.js",
      "FFmpeg",
      "YTDL-Core",
      "Heroku",
    ],
    description: "A Discord bot that plays music from YouTube. ",
    github: "https://github.com/justinc0251/discord-music-bot",
  },
  {
    id: 6,
    image: Work2,
    title: "Wordle Clone",
    link: "https://justinc0251.github.io/wordle-clone/",
    stack: ["React", "JavaScript", "HTML", "CSS"],
    description: "A clone of the popular game Wordle.",
    github: "https://github.com/justinc0251/wordle-clone",
  },
  {
    id: 7,
    image: Work3,
    title: "ParkMe",
    stack: [
      "React",
      "JavaScript",
      "HTML",
      "CSS",
      "Express.js",
      "Postman",
      "Mapbox",
      "Inrix API",
    ],
    description:
      "An interactive parking web app that allows users to find parking spots in real time.",
    github: "https://github.com/danielkazarian/inrix-hack-2022",
  },
  {
    id: 8,
    image: Work4,
    title: "Calculator",
    link: "https://justinc0251.github.io/calculator/",
    stack: ["JavaScript", "HTML", "CSS"],
    description: "A simple calculator.",
    github: "https://github.com/justinc0251/calculator",
  },
  {
    id: 9,
    image: Work5,
    title: "Etch-A-Sketch",
    link: "https://justinc0251.github.io/etch-a-sketch/",
    stack: ["JavaScript", "HTML", "CSS"],
    description: "A simple Etch-A-Sketch.",
    github: "https://github.com/justinc0251/etch-a-sketch",
  },
];
